### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by evshvarov** [daimor/vscode-intersystems-iris#1]

**Comment by daimor** [comment]
At the moment, there is only macOS version is available, and can be downloaded from [releases](https://github.com/daimor/vscode-intersystems-iris/releases)
Download vsix file, and install it to VSCode, by drag-n-drop or Command Install from vsix..

**Comment by daimor** [comment]
updated [readme](https://github.com/daimor/vscode-intersystems-iris#installation)
